// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARZJG8UBk63GF52VAdhkiM8REDTiNu-HE',
    appId: '1:617216651257:web:9ca01d5c4f6a9722db5728',
    messagingSenderId: '617216651257',
    projectId: 'nine2five-63149',
    authDomain: 'nine2five-63149.firebaseapp.com',
    databaseURL: 'https://nine2five-63149-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nine2five-63149.appspot.com',
    measurementId: 'G-P2V3T6V0CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6vvusOvQ85rMTtIojKH0UhRHqRRlt0_A',
    appId: '1:617216651257:android:3a70035993fde495db5728',
    messagingSenderId: '617216651257',
    projectId: 'nine2five-63149',
    databaseURL: 'https://nine2five-63149-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nine2five-63149.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJzUgaY9eoe0D5Y37Wj7gRw3FG9U6r4ts',
    appId: '1:617216651257:ios:f11a4babf9927025db5728',
    messagingSenderId: '617216651257',
    projectId: 'nine2five-63149',
    databaseURL: 'https://nine2five-63149-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nine2five-63149.appspot.com',
    iosClientId: '617216651257-38lct970jomm1p295qo7f6o5fiu21bko.apps.googleusercontent.com',
    iosBundleId: 'com.example.nine2five',
  );
}
